dist: xenial
language: python
python:
  - "2.7"
  - "3.7"
before_install:
  - "sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test -y"
  - "sudo apt-get update -qq"
  - "sudo apt-get install build-essential gcc libboost-dev libgmp-dev libgmpxx* valgrind -y"
install:
  - "pip install ."
script:
  - "./test.sh"
